// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmacy;

namespace Pharmacy.Migrations.Medicine
{
    [DbContext(typeof(MedicineContext))]
    [Migration("20210112113213_UpdatedMedicine")]
    partial class UpdatedMedicine
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pharmacy.Medicine", b =>
                {
                    b.Property<int>("ID_Medicine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count_Medicine")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name_Medicine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price_Medicine")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_Medicine");

                    b.ToTable("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
